### ISSUE TITLE
Add fast forward button

### ISSUE THREAD

**Issue by itaispiegel** [timmh/maxflow#6]
Hey,
It would be great to add a fast-forward button, as the visualization is slow and takes time for large graphs :)

**Comment by timmh** [comment]
Thanks for your suggestion! This is now implemented and deployed.

**Comment by itaispiegel** [comment]
Amazing!!
Though it's a shame it was done right after my algorithms exam 😂

**Comment by timmh** [comment]
Hope you passed nonetheless!
